services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: spring-oficial
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT:  ${REDIS_PORT}

      JWT_SECRET: ${JWT_SECRET}

volumes:
  mysql_data:
